import os
from PIL import Image

# Setup Path Otomatis
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INPUT_PATH = os.path.join(BASE_DIR, "assets", "logo.png")
# Sesuai permintaan terakhirmu, output ke kernel/bootlogo.h
OUTPUT_PATH = os.path.join(BASE_DIR, "kernel", "bootlogo.h")

def generate():
    if not os.path.exists(INPUT_PATH):
        return

    try:
        # Buka gambar (Bisa 32x32, 64x64, dsb)
        img = Image.open(INPUT_PATH).convert("RGBA")
        width, height = img.size
        pixels = img.load()

        # Atur SCALE otomatis agar tidak terlalu besar di layar
        # Jika gambar >= 64px, scale jadi 1 atau 2. Jika 32px, scale 3.
        if width >= 64:
            logo_scale = 1
        elif width >= 32:
            logo_scale = 2
        else:
            logo_scale = 2

        output = [
            "/* SPDX-License-Identifier: GPL-3.0-or-later */",
            "/* Auto-generated by bootlogo.py */",
            "/* Copyright © 2026 Dava - NusaOS */\n",
            "#pragma once\n",
            '#include "api/stdint.h"\n',
            f"#define BOOT_LOGO_WIDTH {width}",
            f"#define BOOT_LOGO_HEIGHT {height}",
            f"#define BOOT_LOGO_SCALE {logo_scale}\n",
            "static const uint32_t boot_logo[] = {"
        ]

        for y in range(height):
            row = []
            for x in range(width):
                r, g, b, a = pixels[x, y]
                # Format 0xAARRGGBB
                if a == 0:
                    val = "0x00000000"
                else:
                    val = f"0x{a:02x}{r:02x}{g:02x}{b:02x}"
                row.append(val)
            
            line = "\t" + ", ".join(row) + ("," if y < height - 1 else "")
            output.append(line)

        output.append("};")

        # Tulis ke kernel/bootlogo.h
        with open(OUTPUT_PATH, "w") as f:
            f.write("\n".join(output))

    except Exception:
        pass

if __name__ == "__main__":
    generate()